name: LunaMoonJewels
version: '${project.version}'
main: org.comp.progiple.lunamoonjewels.LunaMoonJewels
api-version: '1.16'
softdepend:
  - PlaceholderAPI
commands:
  lunamoonjewels:
    aliases:
      - lmjewels
      - lmj
      - lunamoonj
      - points
      - tokens
      - t
      - p
      - jewels
      - j
permissions:
  lmjewels.admin:
    default: op
  lmjewels.pay:
    default: op
  lmjewels.balance:
    default: true
  lmjewels.balance.another:
    default: true